apiVersion: v2
name: theai
description: THEAI - Monitoring & Vulnerability Platform
type: application
version: 1.2.0
appVersion: "1.2.0"
keywords:
  - theai
  - monitoring
  - kubernetes
home: https://github.com/iwebbo/theai
sources:
  - https://github.com/iwebbo/theai
maintainers:
  - name: DevOps Team
    email: aecodinglocal@gmail.com