ingress:
  enabled: true
  className: "nginx"
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
  
  hosts:
    - host: theai.local
      paths:
        - path: /
          pathType: Prefix
          service: frontend
          port: 80
        - path: /api
          pathType: Prefix
          service: backend
          port: 8000
  
  tls:
    enabled: false